Attendee.create(first_name: "Kay", last_name: "Mok", age: 26, likes_beer: true, happy_hour_event_id: 1)
Attendee.create(first_name: "Barack", last_name: "Obama", age: 56, likes_beer: true, happy_hour_event_id: 2)
Attendee.create(first_name: "Michelle", last_name: "Obama", age: 54, likes_beer: false, happy_hour_event_id: 2)
Attendee.create(first_name: "Benedict", last_name: "Cumberbatch", age: 41, likes_beer: false, happy_hour_event_id: 1)
Attendee.create(first_name: "Martin", last_name: "Freeman", age: 46, likes_beer: true, happy_hour_event_id: 1)
HappyHourEvent.create(name: "Sherlock", location: "221B Baker Street", capacity: 30)
HappyHourEvent.create(name: "Swag", location: "Chicago", capacity: 2000)
